services:
    hlsdk:
        build:
            context: .
            dockerfile: hlsdk.Dockerfile
        restart: always
        volumes:
            - "./public:/usr/share/nginx/html/public"
        ports:
            - "8080:80"
