services:
    tf15-client:
        build:
            context: .
            dockerfile: tf15-client.Dockerfile
        restart: always
        volumes:
            - "./public:/usr/share/nginx/html/public"
        ports:
            - "8082:80"
